/* Automatically generated by './build/bin/build-entry.js' */

import chintPrint from '../packages/chint-print/index.js'

const components = [
  chintPrint,
]

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  // version: '1.0.0',
  install,
  chintPrint
}
